# Reference: https://github.com/marketplace/actions/build-and-push-docker-images

name: Build Docker Image
on: 
  # Only run actions when main receives a pull request. This is only a placeholder, need to check Liatrio preference
  pull_request:
    branches:
      - main
jobs:
  # Job name:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # This step is not required, but was recommended
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # Build context is in root file
          context: .
          # Use Dockerfile to build
          file: ./Dockerfile
          # This is currently the build-only version, need to check if it needs to be pushed as well
          push: false
          # Name and tag for build image
          tags: user/simple-web-app:latest



      # In case we need to log into Docker Hub, this is the format needed
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    # Guide recommends using secrets for username and password. Secrets can be accessed in repo settings
      #    # Remove space between $ and { to reactivate secrets variables
      #    username: $ {{secrets.DOCKER_USERNAME}}
      #    password: $ {{secrets.DOCKER_PASSWORD}}

      
